/**
 * Dynaxis Mini App — Creative Editor (non-destructive Composition editor).
 */

export const creativeEditorMiniAppManifest = {
  id: 'dynaxis.creative-editor',
  name: 'Creative Editor',
  description:
    'Non-destructive image Composition editor for Campaign deliverables and Project image Assets. Structured text/image layers, Brand palette hints, server-side PNG export.',
  version: '1.0.0',
  category: 'marketing',
  icon: 'layers',
  status: 'integrated',
  moduleType: 'capability',
  viewId: 'mini-dynaxis-creative-editor',
  route: '/studio/apps/dynaxis.creative-editor',
  entryKey: 'dynaxis.creative-editor',
  permissions: [
    'project:read',
    'assets:read',
    'assets:write',
    'generation:create',
    'generation:read',
    'jobs:create',
    'jobs:read',
    'models:use',
    'brands:read',
    'campaigns:read',
    'campaigns:write',
    'compositions:read',
    'compositions:write',
    'templates:read',
    'templates:write',
    'components:read',
    'components:write',
    'designSystems:read',
    'componentSets:read',
  ],
  requiredCapabilities: [
    'projects',
    'assets',
    'generations',
    'jobs',
    'muapi',
    'database',
    'brands',
    'campaigns',
    'compositions',
    'templates',
    'components',
    'designSystems',
    'componentSets',
  ],
  assetInputs: [
    {
      type: 'image',
      role: 'creative_reference',
      required: false,
      minCount: 0,
      maxCount: 16,
      description: 'Image layers and background replacements',
    },
  ],
  assetOutputs: ['image'],
  modelCapabilities: ['image', 'nano-banana-pro-edit'],
  requiresProjectContext: true,
  requiresGenerationAccess: true,
  requiresAssetWrite: true,
  featureFlags: {
    noPublishing: true,
    noVideo: true,
    noCollaboration: true,
  },
  attribution: {
    source: 'SamurAIGPT/Open-Pomelli',
    license: 'MIT (patterns only)',
    notes:
      'Nine-position presets, copy layers, brand palette, clean-background regen adapted. Prisma/canvas shell discarded.',
  },
};
